package com.lw.wechatplugin.hook;

/* compiled from: WxNames */
public class e {
    public String A;
    public String B;
    public String C;
    public String D;
    public String E;
    public String F;
    public String G;
    public String H;
    public String I;
    public String J;
    public String K;
    public String L;
    public String M;
    public String N;
    public String O;
    public String P;
    public String Q;
    public String R;
    public String S;
    public boolean T = false;
    public String U;
    public String V;
    public String W;
    public String X;
    public String Y;
    public String Z;
    public String a;
    public String aA;
    public String aB;
    public String aC;
    public String aD;
    public String aE;
    public String aF;
    public String aG;
    public String aH;
    public String aI;
    public String aJ;
    public String aK;
    public String aL;
    public String aM;
    public String aN;
    public String aO;
    public String aP;
    public String aQ;
    public String aR;
    public String aS;
    public String aT;
    public String aU;
    public String aV;
    public boolean aW = false;
    public String aX = "com.tencent.mm.plugin.sns.ui.SnsTimeLineUI";
    public String aY;
    public int aZ;
    public String aa;
    public String ab;
    public String ac;
    public String ad;
    public String ae;
    public String af;
    public String ag;
    public String ah;
    public String ai;
    public String aj;
    public String ak;
    public String al;
    public String am;
    public String an;
    public String ao;
    public String ap;
    public String aq;
    public String ar;
    public String as;
    public String at;
    public String au;
    public String av;
    public int aw;
    public String ax;
    public String ay;
    public String az;
    public String b;
    public String ba;
    public String bb;
    public String bc;
    public String bd;
    public String be;
    public String bf;
    public String bg;
    public String bh = "com.tencent.mm.model.bc";
    public String c;
    public String d;
    public String e;
    public String f;
    public String g;
    public String h;
    public String i;
    public String j;
    public String k;
    public String l;
    public String m;
    public String n;
    public int o;
    public String p;
    public String q;
    public String r;
    public String s;
    public String t;
    public String u;
    public String v;
    public String w;
    public String x;
    public String y;
    public String z;

    public e(String str, String str2) {
        this.a = str;
        l();
        if (str2.contains("6.3.15")) {
            h();
        } else if (str2.contains("6.3.16")) {
            k();
        } else if (str2.contains("6.3.18")) {
            j();
        } else if (str2.contains("6.3.22")) {
            i();
        } else if (str2.contains("6.3.23")) {
            g();
        } else if (str2.contains("6.3.25")) {
            f();
        } else if (str2.contains("6.3.27")) {
            e();
        } else if (str2.contains("6.3.28")) {
            d();
        } else if (str2.contains("6.3.30")) {
            c();
        } else if (str2.contains("6.3.31")) {
            c();
        } else if (str2.contains("6.5.2")) {
            b();
        } else if (str2.contains("6.5.3")) {
            a();
        }
    }

    private void a() {
        this.aW = true;
        this.aY = "jUB";
        this.aZ = 2131759452;
        this.ba = "com.tencent.mm.plugin.sns.e.ak.a";
        this.bb = "a";
        this.bc = "com.tencent.mm.plugin.sns.storage.k";
        this.bd = "com.tencent.mm.protocal.c.avr";
        this.be = "field_likeFlag";
        this.bf = "oFl";
        this.bg = "gQL";
        this.aH = "com.tencent.mm.sdk.platformtools.aa";
        this.e = this.a + ".plugin.sns.ui.au";
        this.f = "qK";
        this.g = "jWl";
        this.i = this.a + ".plugin.sns.ui.aq";
        this.k = "bij";
        this.o = 2131758726;
        this.p = null;
        this.q = "ijg";
        this.r = this.a + ".plugin.radar.a.e$d";
        this.s = this.a + ".plugin.radar.ui.RadarViewController";
        this.t = "Q";
        this.u = "b";
        this.v = this.a + ".ui.transmit.SelectConversationUI";
        this.w = this.a + ".ui.transmit.MsgRetransmitUI";
        this.U = "wH";
        this.V = "LX";
        this.x = this.a + ".model.c";
        this.y = null;
        this.z = "wJ";
        this.A = "ek";
        this.B = "field_imgPath";
        this.C = this.a + ".ae.n";
        this.D = "GH";
        this.E = "w";
        this.ap = "wG";
        this.ay = this.a + ".ak.c";
        this.az = "b";
        this.F = this.a + ".plugin.nearby.ui.NearbyFriendsUI";
        this.G = "fHE";
        this.H = "com.tencent.map.geolocation.TencentLocation";
        this.I = "com.tencent.mm.modelgeo.f";
        this.J = "com.tencent.mm.modelgeo.e";
        this.K = "mvR";
        this.L = "gln";
        this.M = "efy";
        this.N = this.a + ".model.k";
        this.O = "xH";
        this.P = this.a + ".pluginsdk.model.m";
        this.Q = this.a + ".model.ak";
        this.R = "vy";
        this.S = "a";
        this.T = true;
        this.W = "aUp";
        this.aj = "mWn";
        this.X = "mWq";
        this.Y = "aXz";
        this.Z = "gkC";
        this.aa = "glb";
        this.ah = "mol";
        this.ai = "mom";
        this.ab = "mIe";
        this.ac = "mIg";
        this.ak = "mHP";
        this.ad = "com.tencent.mm.modelsfs.a";
        this.ae = "cXI";
        this.af = "free";
        this.ag = "j";
        this.al = "heB";
        this.am = "su";
        this.an = "com.tencent.mm.h.a";
        this.aF = "d";
        this.ao = "com.tencent.mm.v.k";
        this.aG = "aG";
        this.bh = "com.tencent.mm.model.bm";
        this.aq = this.a + ".ui.contact.AddressUI.a";
        this.ar = "bys";
        this.as = "oEt";
        this.at = "oEa";
        this.av = null;
        this.aw = 2131759452;
        this.ax = "b";
        this.aB = this.a + ".model.i";
        this.aC = "ej";
        this.aI = this.a + ".storage.at";
        this.aJ = this.a + ".storage.au";
        this.aK = "R";
        this.aL = "field_talker";
        this.aM = "field_isSend";
        this.aN = "field_type";
        this.aO = this.a + ".ui.chatting.ChattingUI.a";
        this.aP = "bhV";
        this.aQ = "hjH";
        this.aR = "hhK";
        this.aS = "hhL";
        this.aT = "oIg";
        this.aU = "a";
        this.aV = "com.tencent.mm.ui.k.b";
    }

    private void b() {
        this.aW = true;
        this.aY = "jUB";
        this.aZ = 2131759452;
        this.ba = "com.tencent.mm.plugin.sns.e.ak.a";
        this.bb = "a";
        this.bc = "com.tencent.mm.plugin.sns.storage.k";
        this.bd = "com.tencent.mm.protocal.c.avr";
        this.be = "field_likeFlag";
        this.bf = "oFl";
        this.bg = "gQL";
        this.aH = "com.tencent.mm.sdk.platformtools.aa";
        this.e = this.a + ".plugin.sns.ui.au";
        this.f = "qK";
        this.g = "jWl";
        this.i = this.a + ".plugin.sns.ui.aq";
        this.k = "bij";
        this.o = 2131758726;
        this.p = null;
        this.q = "ijg";
        this.r = this.a + ".plugin.radar.a.e$d";
        this.s = this.a + ".plugin.radar.ui.RadarViewController";
        this.t = "Q";
        this.u = "b";
        this.v = this.a + ".ui.transmit.SelectConversationUI";
        this.w = this.a + ".ui.transmit.MsgRetransmitUI";
        this.U = "wH";
        this.V = "LX";
        this.x = this.a + ".model.c";
        this.y = null;
        this.z = "wJ";
        this.A = "ek";
        this.B = "field_imgPath";
        this.C = this.a + ".ae.n";
        this.D = "GH";
        this.E = "w";
        this.ap = "wG";
        this.ay = this.a + ".ak.c";
        this.az = "b";
        this.F = this.a + ".plugin.nearby.ui.NearbyFriendsUI";
        this.G = "fHE";
        this.H = "com.tencent.map.geolocation.TencentLocation";
        this.I = "com.tencent.mm.modelgeo.f";
        this.J = "com.tencent.mm.modelgeo.e";
        this.K = "mvR";
        this.L = "gln";
        this.M = "efy";
        this.N = this.a + ".model.k";
        this.O = "xH";
        this.P = this.a + ".pluginsdk.model.m";
        this.Q = this.a + ".model.ak";
        this.R = "vy";
        this.S = "a";
        this.T = true;
        this.W = "aUp";
        this.aj = "mWn";
        this.X = "mWq";
        this.Y = "aXz";
        this.Z = "gkC";
        this.aa = "glb";
        this.ah = "mol";
        this.ai = "mom";
        this.ab = "mIe";
        this.ac = "mIg";
        this.ak = "mHP";
        this.ad = "com.tencent.mm.modelsfs.a";
        this.ae = "cXI";
        this.af = "free";
        this.ag = "j";
        this.al = "heB";
        this.am = "su";
        this.an = "com.tencent.mm.h.a";
        this.aF = "d";
        this.ao = "com.tencent.mm.v.k";
        this.aG = "aG";
        this.bh = "com.tencent.mm.model.bm";
        this.aq = this.a + ".ui.contact.AddressUI.a";
        this.ar = "bys";
        this.as = "oEt";
        this.at = "oEa";
        this.av = null;
        this.aw = 2131759452;
        this.ax = "b";
        this.aB = this.a + ".model.i";
        this.aC = "ej";
        this.aI = this.a + ".storage.at";
        this.aJ = this.a + ".storage.au";
        this.aK = "R";
        this.aL = "field_talker";
        this.aM = "field_isSend";
        this.aN = "field_type";
        this.aO = this.a + ".ui.chatting.ChattingUI.a";
        this.aP = "bhV";
        this.aQ = "hjH";
        this.aR = "hhK";
        this.aS = "hhL";
        this.aT = "oIg";
        this.aU = "a";
        this.aV = "com.tencent.mm.ui.k.b";
    }

    private void c() {
        this.aW = true;
        this.aY = "jiU";
        this.aZ = 2131759433;
        this.ba = "com.tencent.mm.plugin.sns.e.ak.a";
        this.bb = "a";
        this.bc = "com.tencent.mm.plugin.sns.j.k";
        this.bd = "com.tencent.mm.protocal.b.auu";
        this.be = "field_likeFlag";
        this.bf = "nKw";
        this.bg = "gxb";
        this.aH = "com.tencent.mm.sdk.platformtools.aa";
        this.e = this.a + ".plugin.sns.ui.ar";
        this.f = "pQ";
        this.g = "mVending";
        this.i = this.a + ".plugin.sns.ui.ao";
        this.k = "bhq";
        this.o = 2131758831;
        this.p = null;
        this.q = "hAO";
        this.r = this.a + ".plugin.radar.a.e$d";
        this.s = this.a + ".plugin.radar.ui.RadarViewController";
        this.t = "M";
        this.u = "b";
        this.v = this.a + ".ui.transmit.SelectConversationUI";
        this.w = this.a + ".ui.transmit.MsgRetransmitUI";
        this.U = "xf";
        this.V = "Kd";
        this.x = this.a + ".model.ah";
        this.y = "zh";
        this.z = "xh";
        this.A = "eb";
        this.B = "field_imgPath";
        this.C = this.a + ".ag.n";
        this.D = "Gj";
        this.E = "v";
        this.ap = "xe";
        this.ay = this.a + ".am.b.c";
        this.az = "b";
        this.F = this.a + ".plugin.nearby.ui.NearbyFriendsUI";
        this.G = "fqO";
        this.H = "com.tencent.map.geolocation.TencentLocation";
        this.I = "com.tencent.mm.modelgeo.f";
        this.J = "com.tencent.mm.modelgeo.e";
        this.K = "lFs";
        this.L = "fRI";
        this.M = "lko";
        this.N = this.a + ".model.h";
        this.O = "xW";
        this.P = this.a + ".pluginsdk.model.l";
        this.Q = this.a + ".model.ah";
        this.R = "vS";
        this.S = "a";
        this.T = true;
        this.W = "aPi";
        this.aj = "mfl";
        this.X = "mfo";
        this.Y = "aXh";
        this.Z = "fRb";
        this.aa = "fRA";
        this.ah = "lxJ";
        this.ai = "lxK";
        this.ab = "lRi";
        this.ac = "lRk";
        this.ak = "lQT";
        this.ad = "com.tencent.mm.modelsfs.a";
        this.ae = "cTF";
        this.af = "free";
        this.ag = "j";
        this.al = "gKZ";
        this.am = "sN";
        this.an = "com.tencent.mm.h.a";
        this.aF = "c";
        this.ao = "com.tencent.mm.v.k";
        this.aG = "aH";
        this.bh = "com.tencent.mm.model.bg";
        this.aq = this.a + ".ui.contact.AddressUI.a";
        this.ar = "bse";
        this.as = "nJE";
        this.at = "nJl";
        this.av = null;
        this.aw = 2131759433;
        this.ax = "b";
        this.aB = this.a + ".model.f";
        this.aC = "em";
        this.aI = this.a + ".storage.ak";
        this.aJ = this.a + ".storage.al";
        this.aK = "I";
        this.aL = "field_talker";
        this.aM = "field_isSend";
        this.aN = "field_type";
        this.aO = this.a + ".ui.chatting.ChattingUI.a";
        this.aP = "nrj";
        this.aQ = "gQd";
        this.aR = "gOi";
        this.aS = "gOj";
        this.aT = "nNm";
        this.aU = "a";
        this.aV = "com.tencent.mm.ui.k.b";
    }

    private void d() {
        this.aW = true;
        this.aY = "jer";
        this.aZ = 2131759410;
        this.ba = "com.tencent.mm.plugin.sns.e.ak.a";
        this.bb = "a";
        this.bc = "com.tencent.mm.plugin.sns.j.k";
        this.bd = "com.tencent.mm.protocal.b.aui";
        this.be = "field_likeFlag";
        this.bf = "nFM";
        this.bg = "gsD";
        this.aH = "com.tencent.mm.sdk.platformtools.aa";
        this.e = this.a + ".plugin.sns.ui.ar";
        this.f = "pH";
        this.g = "mVending";
        this.i = this.a + ".plugin.sns.ui.ao";
        this.k = "bhq";
        this.o = 2131758807;
        this.p = null;
        this.q = "hwq";
        this.r = this.a + ".plugin.radar.a.e$d";
        this.s = this.a + ".plugin.radar.ui.RadarViewController";
        this.t = "M";
        this.u = "b";
        this.v = this.a + ".ui.transmit.SelectConversationUI";
        this.w = this.a + ".ui.transmit.MsgRetransmitUI";
        this.U = "xc";
        this.V = "JK";
        this.x = this.a + ".model.ah";
        this.y = "ze";
        this.z = "xe";
        this.A = "dZ";
        this.B = "field_imgPath";
        this.C = this.a + ".ag.n";
        this.D = "Gg";
        this.E = "u";
        this.ap = "xb";
        this.ay = this.a + ".am.b.c";
        this.az = "b";
        this.F = this.a + ".plugin.nearby.ui.NearbyFriendsUI";
        this.G = "fmq";
        this.H = "com.tencent.map.geolocation.TencentLocation";
        this.I = "com.tencent.mm.modelgeo.f";
        this.J = "com.tencent.mm.modelgeo.e";
        this.K = "lAW";
        this.L = "fNi";
        this.M = "lfW";
        this.N = this.a + ".model.h";
        this.O = "xT";
        this.P = this.a + ".pluginsdk.model.l";
        this.Q = this.a + ".model.ah";
        this.R = "vP";
        this.S = "a";
        this.T = true;
        this.W = "aOH";
        this.aj = "maF";
        this.X = "maI";
        this.Y = "aXh";
        this.Z = "fMB";
        this.aa = "fNa";
        this.ah = "ltm";
        this.ai = "ltn";
        this.ab = "lMG";
        this.ac = "lMI";
        this.ak = "lMr";
        this.ad = "com.tencent.mm.modelsfs.a";
        this.ae = "cTi";
        this.af = "free";
        this.ag = "j";
        this.al = "gGB";
        this.am = "sL";
        this.an = "com.tencent.mm.h.a";
        this.aF = "c";
        this.ao = "com.tencent.mm.v.k";
        this.aG = "aH";
        this.bh = "com.tencent.mm.model.bg";
        this.aq = this.a + ".ui.contact.AddressUI.a";
        this.ar = "brz";
        this.as = "nEU";
        this.at = "nEB";
        this.av = null;
        this.aw = 2131759410;
        this.ax = "b";
        this.aB = this.a + ".model.f";
        this.aC = "em";
        this.aI = this.a + ".storage.ak";
        this.aJ = this.a + ".storage.al";
        this.aK = "I";
        this.aL = "field_talker";
        this.aM = "field_isSend";
        this.aN = "field_type";
        this.aO = this.a + ".ui.chatting.ChattingUI.a";
        this.aP = "nmv";
        this.aQ = "gLF";
        this.aR = "gJK";
        this.aS = "gJL";
        this.aT = "nIC";
        this.aU = "a";
        this.aV = "com.tencent.mm.ui.k.b";
    }

    private void e() {
        this.aW = true;
        this.aY = "iQi";
        this.aZ = 2131759301;
        this.ba = "com.tencent.mm.plugin.sns.e.ak.a";
        this.bb = "a";
        this.bc = "com.tencent.mm.plugin.sns.i.k";
        this.bd = "com.tencent.mm.protocal.b.ass";
        this.be = "field_likeFlag";
        this.bf = "nlG";
        this.bg = "ggp";
        this.aH = "com.tencent.mm.sdk.platformtools.aa";
        this.e = this.a + ".plugin.sns.ui.as";
        this.f = "pt";
        this.g = "iRH";
        this.i = this.a + ".plugin.sns.ui.ap";
        this.k = "bgP";
        this.o = 2131758709;
        this.p = null;
        this.q = "hke";
        this.r = this.a + ".plugin.radar.a.e$d";
        this.s = this.a + ".plugin.radar.ui.RadarViewController";
        this.t = "M";
        this.u = "b";
        this.v = this.a + ".ui.transmit.SelectConversationUI";
        this.w = this.a + ".ui.transmit.MsgRetransmitUI";
        this.U = "vV";
        this.V = "IU";
        this.x = this.a + ".model.ah";
        this.y = "yi";
        this.z = "vX";
        this.A = "dV";
        this.B = "field_imgPath";
        this.C = this.a + ".af.n";
        this.D = "Fh";
        this.E = "s";
        this.ap = "vU";
        this.ay = this.a + ".ak.b.c";
        this.az = "b";
        this.F = this.a + ".plugin.nearby.ui.NearbyFriendsUI";
        this.G = "fbL";
        this.H = "com.tencent.map.geolocation.TencentLocation";
        this.I = "com.tencent.mm.modelgeo.f";
        this.J = "com.tencent.mm.modelgeo.e";
        this.K = "liS";
        this.L = "fCd";
        this.M = "kOs";
        this.N = this.a + ".model.h";
        this.O = "wK";
        this.P = this.a + ".pluginsdk.model.l";
        this.Q = this.a + ".model.ah";
        this.R = "yj";
        this.S = "a";
        this.T = true;
        this.W = "aLQ";
        this.aj = "lIj";
        this.X = "lIm";
        this.Y = "aWV";
        this.Z = "fBw";
        this.aa = "fBV";
        this.ab = "luD";
        this.ac = "luF";
        this.ah = "lbh";
        this.ai = "lbi";
        this.ak = "luo";
        this.ad = "com.tencent.mm.modelsfs.a";
        this.ae = "cOI";
        this.af = "free";
        this.ag = "j";
        this.al = "guw";
        this.am = "sG";
        this.an = "com.tencent.mm.h.a";
        this.aF = "e";
        this.ao = "com.tencent.mm.u.k";
        this.aG = "aG";
        this.aq = this.a + ".ui.contact.AddressUI.a";
        this.ar = "boa";
        this.as = "nkO";
        this.at = "nkv";
        this.av = null;
        this.aw = 2131759301;
        this.ax = "b";
        this.aB = this.a + ".model.f";
        this.aC = "eg";
        this.aI = this.a + ".storage.ak";
        this.aJ = this.a + ".storage.al";
        this.aK = "I";
        this.aL = "field_talker";
        this.aM = "field_isSend";
        this.aN = "field_type";
        this.aO = this.a + ".ui.chatting.ChattingUI.a";
        this.aP = "mSL";
        this.aQ = "gzB";
        this.aR = "gxH";
        this.aS = "gxI";
        this.aT = "nos";
        this.aU = "a";
        this.aV = "com.tencent.mm.ui.j.b";
    }

    private void f() {
        this.aW = true;
        this.aY = "ieI";
        this.aZ = 2131759186;
        this.ba = "com.tencent.mm.plugin.sns.e.ak.a";
        this.bb = "a";
        this.bc = "com.tencent.mm.plugin.sns.i.k";
        this.bd = "com.tencent.mm.protocal.b.ark";
        this.be = "field_likeFlag";
        this.bf = "mxi";
        this.bg = "fuD";
        this.aH = "com.tencent.mm.sdk.platformtools.aa";
        this.e = this.a + ".plugin.sns.ui.ar";
        this.f = "nP";
        this.g = "mVending";
        this.i = this.a + ".plugin.sns.ui.ao";
        this.k = "aPy";
        this.o = 2131758596;
        this.p = null;
        this.q = "gyC";
        this.r = this.a + ".plugin.radar.a.e$d";
        this.s = this.a + ".plugin.radar.ui.RadarViewController";
        this.t = "L";
        this.u = "b";
        this.v = this.a + ".ui.transmit.SelectConversationUI";
        this.w = this.a + ".ui.transmit.MsgRetransmitUI";
        this.U = "tr";
        this.V = "He";
        this.x = this.a + ".model.ah";
        this.y = "vE";
        this.z = "tt";
        this.A = "dU";
        this.B = "field_imgPath";
        this.C = this.a + ".ae.n";
        this.D = "Cx";
        this.E = "r";
        this.ap = "tq";
        this.ay = this.a + ".aj.b.c";
        this.az = "b";
        this.F = this.a + ".plugin.nearby.ui.NearbyFriendsUI";
        this.G = "epD";
        this.H = "com.tencent.map.geolocation.TencentLocation";
        this.I = "com.tencent.mm.modelgeo.f";
        this.J = "com.tencent.mm.modelgeo.e";
        this.K = "kwG";
        this.L = "eQf";
        this.M = "kcE";
        this.N = this.a + ".model.h";
        this.O = "ug";
        this.P = this.a + ".pluginsdk.model.l";
        this.Q = this.a + ".model.ah";
        this.R = "vF";
        this.S = "a";
        this.T = true;
        this.W = "aFz";
        this.aj = "kVC";
        this.X = "kVF";
        this.Y = "aFG";
        this.Z = "ePy";
        this.aa = "ePX";
        this.ah = "koW";
        this.ai = "koX";
        this.ak = "kHP";
        this.al = "fIK";
        this.am = "pF";
        this.an = "com.tencent.mm.h.a";
        this.aF = "d";
        this.ao = "com.tencent.mm.t.j";
        this.aG = "av";
        this.aq = this.a + ".ui.contact.AddressUI.a";
        this.ar = "bhz";
        this.as = "mwq";
        this.at = "mvX";
        this.av = null;
        this.aw = 2131759186;
        this.ax = "b";
        this.aB = this.a + ".model.f";
        this.aC = "ef";
        this.aI = this.a + ".storage.ak";
        this.aJ = this.a + ".storage.al";
        this.aK = "I";
        this.aL = "field_talker";
        this.aM = "field_isSend";
        this.aN = "field_type";
        this.aO = this.a + ".ui.chatting.ChattingUI.a";
        this.aP = "mfH";
        this.aQ = "fNP";
        this.aR = "fLV";
        this.aS = "fLW";
        this.aT = "mzU";
        this.aU = "a";
        this.aV = "com.tencent.mm.ui.j.b";
    }

    private void g() {
        this.aW = true;
        this.aY = "idn";
        this.aZ = 2131759175;
        this.ba = "com.tencent.mm.plugin.sns.e.ak.a";
        this.bb = "a";
        this.bc = "com.tencent.mm.plugin.sns.i.k";
        this.bd = "com.tencent.mm.protocal.b.ark";
        this.be = "field_likeFlag";
        this.bf = "mvy";
        this.bg = "ftE";
        this.aH = "com.tencent.mm.sdk.platformtools.aa";
        this.e = this.a + ".plugin.sns.ui.ar";
        this.f = "nO";
        this.g = "mVending";
        this.i = this.a + ".plugin.sns.ui.ao";
        this.k = "aPy";
        this.o = 2131758589;
        this.p = null;
        this.q = "gxD";
        this.r = this.a + ".plugin.radar.a.e$d";
        this.s = this.a + ".plugin.radar.ui.RadarViewController";
        this.t = "L";
        this.u = "b";
        this.v = this.a + ".ui.transmit.SelectConversationUI";
        this.w = this.a + ".ui.transmit.MsgRetransmitUI";
        this.U = "tq";
        this.V = "Hg";
        this.x = this.a + ".model.ah";
        this.y = "vD";
        this.z = "ts";
        this.A = "dT";
        this.B = "field_imgPath";
        this.C = this.a + ".ae.n";
        this.D = "Cy";
        this.E = "r";
        this.ap = "tp";
        this.ay = this.a + ".aj.b.c";
        this.az = "b";
        this.F = this.a + ".plugin.nearby.ui.NearbyFriendsUI";
        this.G = "epk";
        this.H = "com.tencent.map.geolocation.TencentLocation";
        this.I = "com.tencent.mm.modelgeo.f";
        this.J = "com.tencent.mm.modelgeo.e";
        this.K = "kvj";
        this.L = "ePB";
        this.M = "kbg";
        this.N = this.a + ".model.h";
        this.O = "uf";
        this.P = this.a + ".pluginsdk.model.l";
        this.Q = this.a + ".model.ah";
        this.R = "vE";
        this.S = "a";
        this.T = true;
        this.W = "aFt";
        this.aj = "kUe";
        this.X = "kUh";
        this.Y = "aFG";
        this.Z = "eOW";
        this.aa = "ePt";
        this.ah = "knz";
        this.ai = "knA";
        this.ak = "kGs";
        this.al = "fHL";
        this.am = "pE";
        this.an = "com.tencent.mm.h.a";
        this.aF = "d";
        this.ao = "com.tencent.mm.t.j";
        this.aG = "av";
        this.aq = this.a + ".ui.contact.AddressUI.a";
        this.ar = "bhr";
        this.as = "muG";
        this.at = "mun";
        this.av = null;
        this.aw = 2131759175;
        this.ax = "b";
        this.aB = this.a + ".model.f";
        this.aC = "ef";
        this.aE = "kT";
        this.aI = this.a + ".storage.ak";
        this.aJ = this.a + ".storage.al";
        this.aK = "I";
        this.aL = "field_talker";
        this.aM = "field_isSend";
        this.aN = "field_type";
        this.aO = this.a + ".ui.chatting.ChattingUI.a";
        this.aP = "mdX";
        this.aQ = "fMQ";
        this.aR = "fKW";
        this.aS = "fKX";
        this.aT = "myk";
        this.aU = "a";
        this.aV = "com.tencent.mm.ui.j.b";
    }

    private void h() {
        this.aI = this.a + ".storage.aq";
        this.aJ = this.a + ".storage.ah";
        this.aK = "E";
        this.aL = "field_talker";
        this.aM = "field_isSend";
        this.aN = "field_type";
        this.aO = this.a + ".ui.chatting.ChattingUI.a";
        this.aP = "kLF";
        this.aQ = "eTY";
        this.aR = "eRP";
        this.aS = "eRQ";
    }

    private void i() {
        this.aW = true;
        this.aY = "hyG";
        this.aZ = 2131759125;
        this.ba = "com.tencent.mm.plugin.sns.e.ak.a";
        this.bb = "a";
        this.bc = "com.tencent.mm.plugin.sns.i.k";
        this.bd = "com.tencent.mm.protocal.b.aqk";
        this.be = "field_likeFlag";
        this.bf = "lJq";
        this.bg = "ePU";
        this.aH = "com.tencent.mm.sdk.platformtools.aa";
        this.e = this.a + ".plugin.sns.ui.ar";
        this.f = "ni";
        this.g = "mVending";
        this.i = this.a + ".plugin.sns.ui.ao";
        this.k = "aon";
        this.o = 2131758538;
        this.p = null;
        this.q = "fTJ";
        this.r = this.a + ".plugin.radar.a.e$d";
        this.s = this.a + ".plugin.radar.ui.RadarViewController";
        this.t = "I";
        this.u = "b";
        this.v = this.a + ".ui.transmit.SelectConversationUI";
        this.w = this.a + ".ui.transmit.MsgRetransmitUI";
        this.x = this.a + ".model.ah";
        this.y = "tE";
        this.z = "rt";
        this.A = "dQ";
        this.B = "field_imgPath";
        this.C = this.a + ".ae.n";
        this.D = "Ay";
        this.E = "q";
        this.U = "rr";
        this.V = "GD";
        this.ap = "rq";
        this.ay = this.a + ".aj.b.c";
        this.az = "b";
        this.F = this.a + ".plugin.nearby.ui.NearbyFriendsUI";
        this.G = "dMS";
        this.H = "com.tencent.map.geolocation.TencentLocation";
        this.I = "com.tencent.mm.modelgeo.f";
        this.J = "com.tencent.mm.modelgeo.e";
        this.K = "jNd";
        this.L = "emC";
        this.M = "jtx";
        this.N = this.a + ".model.h";
        this.O = "sg";
        this.P = this.a + ".pluginsdk.model.l";
        this.Q = this.a + ".model.ah";
        this.R = "tF";
        this.S = "a";
        this.T = true;
        this.W = "aCD";
        this.aj = "klf";
        this.X = "kli";
        this.Y = "aez";
        this.Z = "elX";
        this.aa = "emu";
        this.ah = "jFu";
        this.ai = "jFv";
        this.ak = "jYg";
        this.al = "fdV";
        this.am = "nA";
        this.an = "com.tencent.mm.h.a";
        this.aF = "d";
        this.ao = "com.tencent.mm.t.j";
        this.aG = "aj";
        this.aq = this.a + ".ui.contact.AddressUI.a";
        this.ar = "beA";
        this.as = "lIy";
        this.at = "lIf";
        this.av = null;
        this.aw = 2131759125;
        this.ax = "b";
        this.aB = this.a + ".model.f";
        this.aC = "dT";
        this.aE = "kT";
        this.aI = this.a + ".storage.ai";
        this.aJ = this.a + ".storage.aj";
        this.aK = "H";
        this.aL = "field_talker";
        this.aM = "field_isSend";
        this.aN = "field_type";
        this.aO = this.a + ".ui.chatting.ChattingUI.a";
        this.aP = "lrK";
        this.aQ = "fjo";
        this.aR = "fhg";
        this.aS = "fhh";
        this.aT = "lMg";
        this.aU = "a";
        this.aV = "com.tencent.mm.ui.j.b";
    }

    private void j() {
        this.aH = "com.tencent.mm.sdk.platformtools.z";
        this.e = this.a + ".plugin.sns.ui.an";
        this.f = "mY";
        this.g = "mVending";
        this.i = this.a + ".plugin.sns.ui.ak";
        this.k = "aoI";
        this.o = 2131758513;
        this.p = null;
        this.q = "fQe";
        this.r = this.a + ".plugin.radar.a.c$d";
        this.s = this.a + ".plugin.radar.ui.RadarViewController";
        this.t = "I";
        this.u = "b";
        this.v = this.a + ".ui.transmit.SelectConversationUI";
        this.w = this.a + ".ui.transmit.MsgRetransmitUI";
        this.x = this.a + ".model.ah";
        this.y = "tu";
        this.z = "rj";
        this.A = "dJ";
        this.B = "field_imgPath";
        this.C = this.a + ".ad.n";
        this.D = "Ar";
        this.E = "q";
        this.U = "rh";
        this.V = "FP";
        this.ap = "rg";
        this.F = this.a + ".plugin.nearby.ui.NearbyFriendsUI";
        this.G = "dKg";
        this.H = "com.tencent.map.geolocation.TencentLocation";
        this.I = "com.tencent.mm.modelgeo.f";
        this.J = "com.tencent.mm.modelgeo.e";
        this.K = "jAI";
        this.L = "ejE";
        this.M = "jhe";
        this.N = this.a + ".model.h";
        this.O = "rW";
        this.P = this.a + ".pluginsdk.model.l";
        this.Q = this.a + ".model.ah";
        this.R = "tv";
        this.S = "d";
        this.W = "aBK";
        this.aj = "jYI";
        this.X = "jYL";
        this.Y = "afb";
        this.Z = "eiZ";
        this.aa = "ejw";
        this.ah = "jsT";
        this.ai = "jsU";
        this.ak = "jLG";
        this.al = "faL";
        this.am = "nM";
        this.aF = "d";
        this.aG = "ak";
        this.ao = "com.tencent.mm.s.j";
        this.aq = this.a + ".ui.contact.AddressUI.a";
        this.ar = "bcS";
        this.as = "lwc";
        this.at = "lvJ";
        this.av = null;
        this.aw = 2131759065;
        this.ax = "b";
        this.ay = this.a + ".ai.b.c";
        this.az = "b";
        this.aB = this.a + ".model.f";
        this.aC = "dU";
        this.aE = "kT";
        this.aI = this.a + ".storage.ai";
        this.aJ = this.a + ".storage.aj";
        this.aK = "H";
        this.aL = "field_talker";
        this.aM = "field_isSend";
        this.aN = "field_type";
        this.aO = this.a + ".ui.chatting.ChattingUI.a";
        this.aP = "lfo";
        this.aQ = "ffX";
        this.aR = "fdR";
        this.aS = "fdS";
        this.aT = "fEy";
        this.aU = "a";
        this.aV = "com.tencent.mm.ui.j.b";
    }

    private void k() {
        this.e = this.a + ".plugin.sns.ui.ap";
        this.f = "lR";
        this.g = "hiB";
        this.i = this.a + ".plugin.sns.ui.am";
        this.k = "aoY";
        this.r = this.a + ".plugin.radar.a.c$d";
        this.s = this.a + ".plugin.radar.ui.RadarViewController";
        this.t = "G";
        this.u = "b";
        this.v = this.a + ".ui.transmit.SelectConversationUI";
        this.w = this.a + ".ui.transmit.MsgRetransmitUI";
        this.x = this.a + ".model.ah";
        this.y = "sR";
        this.z = "qJ";
        this.A = "dE";
        this.B = "field_imgPath";
        this.C = this.a + ".ad.n";
        this.D = "zK";
        this.E = "r";
        this.U = "qH";
        this.V = "EU";
        this.ap = "qG";
        this.F = this.a + ".plugin.nearby.ui.NearbyFriendsUI";
        this.G = "dFz";
        this.H = "com.tencent.map.geolocation.TencentLocation";
        this.I = "com.tencent.mm.modelgeo.f";
        this.J = "com.tencent.mm.modelgeo.e";
        this.K = "jqh";
        this.L = "eeQ";
        this.M = "iWN";
        this.N = this.a + ".model.h";
        this.O = "rv";
        this.P = this.a + ".pluginsdk.model.l";
        this.Q = this.a + ".model.ah";
        this.R = "sS";
        this.S = "d";
        this.W = "azP";
        this.aj = "jNJ";
        this.X = "jNM";
        this.Y = "afr";
        this.Z = "eel";
        this.aa = "eeJ";
        this.ah = "jiA";
        this.ai = "jiB";
        this.ak = "jAV";
        this.al = "eUn";
        this.am = "nO";
        this.ao = "com.tencent.mm.s.j";
        this.aq = this.a + ".ui.contact.AddressUI.a";
        this.ar = "bam";
        this.as = "llq";
        this.at = "lkX";
        this.av = "aBv";
        this.aw = 2131168637;
        this.ax = "b";
        this.ay = this.a + ".ai.b.c";
        this.az = "b";
        this.aB = this.a + ".model.f";
        this.aC = "dZ";
        this.aE = "kT";
        this.aI = this.a + ".storage.aq";
        this.aJ = this.a + ".storage.ah";
        this.aK = "H";
        this.aL = "field_talker";
        this.aM = "field_isSend";
        this.aN = "field_type";
        this.aO = this.a + ".ui.chatting.ChattingUI.a";
        this.aP = "kUF";
        this.aQ = "eZA";
        this.aR = "eXr";
        this.aS = "eXs";
        this.aT = "fxT";
        this.aU = "a";
        this.aV = "com.tencent.mm.ui.j.b";
    }

    private void l() {
        this.aH = "com.tencent.mm.sdk.platformtools.y";
        this.aA = this.a + ".plugin.chatroom.ui.ChatroomInfoUI";
        this.c = this.a + ".ui.LauncherUI";
        this.b = this.a + ".plugin.profile.ui.ContactInfoUI";
        this.d = this.a + ".plugin.sns.ui.SightUploadUI";
        this.e = this.a + ".plugin.sns.ui.ao";
        this.f = "lT";
        this.g = "hcp";
        this.h = "mContext";
        this.i = this.a + ".plugin.sns.ui.ak";
        this.j = "getItem";
        this.k = "aoU";
        this.l = this.a + ".plugin.radar.ui.RadarSearchUI";
        this.n = this.a + ".plugin.radar.ui.RadarMemberView";
        this.m = this.a + ".plugin.radar.ui.RadarMemberView$a";
        this.p = "setListener";
        this.r = this.a + ".plugin.radar.a.c$d";
        this.s = this.a + ".plugin.radar.ui.RadarViewController";
        this.t = "G";
        this.u = "b";
        this.v = this.a + ".ui.transmit.SelectConversationUI";
        this.w = this.a + ".ui.transmit.MsgRetransmitUI";
        this.x = this.a + ".model.ah";
        this.y = "sP";
        this.z = "qH";
        this.A = "dB";
        this.B = "field_imgPath";
        this.C = this.a + ".ab.n";
        this.D = "zA";
        this.E = "r";
        this.ap = "qE";
        this.F = this.a + ".plugin.nearby.ui.NearbyFriendsUI";
        this.G = "dDd";
        this.H = "com.tencent.map.geolocation.TencentLocation";
        this.I = "com.tencent.mm.modelgeo.f";
        this.J = "com.tencent.mm.modelgeo.e";
        this.K = "jhU";
        this.L = "ebx";
        this.M = "iON";
        this.N = this.a + ".model.h";
        this.O = "rt";
        this.P = this.a + ".pluginsdk.model.l";
        this.Q = this.a + ".model.ah";
        this.R = "sQ";
        this.S = "d";
        this.U = "qF";
        this.V = "Ev";
        this.W = "ayW";
        this.aj = "jFi";
        this.X = "jFl";
        this.Y = "aft";
        this.Z = "eaV";
        this.aa = "ebm";
        this.ah = "jat";
        this.ai = "jau";
        this.ak = "jsw";
        this.al = "eOm";
        this.am = "nP";
        this.an = "com.tencent.mm.g.a";
        this.aF = "e";
        this.aG = "K";
        this.ao = "com.tencent.mm.r.j";
        this.aq = this.a + ".ui.contact.AddressUI.a";
        this.ar = "aZf";
        this.as = "lci";
        this.at = "lbP";
        this.au = this.a + ".plugin.sns.ui.SnsUserUI";
        this.av = "aAB";
        this.aw = 2131168568;
        this.ax = "b";
        this.ay = this.a + ".ag.b.c";
        this.az = "b";
        this.aB = this.a + ".model.f";
        this.aC = "dW";
        this.aD = this.a + ".sdk.platformtools.ba";
        this.aE = "kO";
        this.aT = "fsp";
        this.aU = "a";
        this.aV = "com.tencent.mm.ui.j.b";
    }
}
